import type { FinanceToolDefinition } from "./registry";
import type { DebtService } from "@/servers/finance-mcp/services";
import { isExpectedFinanceError, MONEY_PATTERN } from "@/servers/finance-mcp/services";
import type { McpCallToolResult } from "@/shared/mcp";
const id = { type: "integer", minimum: 1 } as const; const money = { type: "string", pattern: MONEY_PATTERN } as const; const date = { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" } as const; const text = { type: "string", minLength: 1 } as const; const priority = { type: "string", enum: ["LOW", "MEDIUM", "HIGH"] } as const;
async function run<T>(operation: () => Promise<T>, text_: string, key: string): Promise<McpCallToolResult> { try { const value = await operation(); return { content: [{ type: "text", text: text_ }], structuredContent: { currency: "GTQ", [key]: value } }; } catch (error) { if (!isExpectedFinanceError(error)) throw error; return { content: [{ type: "text", text: error.message }], isError: true }; } }
export function createDebtTools(service: DebtService): FinanceToolDefinition[] { return [
  { name: "record_debt", description: "Record a debt.", isWriteOperation: true, inputSchema: { type: "object", additionalProperties: false, required: ["description", "amount", "dueDate", "priority"], properties: { description: text, amount: money, dueDate: date, priority } }, handler: (a) => run(() => service.recordDebt(a as never), "Debt recorded.", "debt") },
  { name: "list_debts", description: "List debts.", isWriteOperation: false, inputSchema: { type: "object", additionalProperties: false, properties: { status: { type: "string", enum: ["PENDING", "PAID"] }, priority, dueBefore: date } }, handler: (a) => run(() => service.listDebts(a as never), "Debts listed.", "debts") },
  { name: "update_debt", description: "Update a debt.", isWriteOperation: true, inputSchema: { type: "object", additionalProperties: false, required: ["debtId"], anyOf: [{ properties: { description: text }, required: ["description"] }, { properties: { amount: money }, required: ["amount"] }, { properties: { dueDate: date }, required: ["dueDate"] }, { properties: { priority }, required: ["priority"] }], properties: { debtId: id, description: text, amount: money, dueDate: date, priority } }, handler: (a) => run(() => service.updateDebt(a as never), "Debt updated.", "debt") },
  { name: "mark_debt_paid", description: "Mark a debt as paid.", isWriteOperation: true, inputSchema: { type: "object", additionalProperties: false, required: ["debtId"], properties: { debtId: id } }, handler: (a) => run(() => service.markDebtPaid(a.debtId as number), "Debt marked as paid.", "debt") },
  { name: "delete_debt", description: "Delete a debt.", isWriteOperation: true, inputSchema: { type: "object", additionalProperties: false, required: ["debtId"], properties: { debtId: id } }, handler: (a) => run(() => service.deleteDebt(a.debtId as number), "Debt deleted.", "debt") },
]; }
