import type { FinanceToolDefinition } from "./registry";
import type { ReceivableService } from "@/servers/finance-mcp/services";
import { isExpectedFinanceError, MONEY_PATTERN } from "@/servers/finance-mcp/services";
import type { McpCallToolResult } from "@/shared/mcp";
const id = { type: "integer", minimum: 1 } as const; const money = { type: "string", pattern: MONEY_PATTERN } as const; const date = { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" } as const; const text = { type: "string", minLength: 1 } as const; const confidence = { type: "string", enum: ["CONFIRMED", "UNCONFIRMED"] } as const;
async function run<T>(operation: () => Promise<T>, message: string, key: string): Promise<McpCallToolResult> { try { const value = await operation(); return { content: [{ type: "text", text: message }], structuredContent: { currency: "GTQ", [key]: value } }; } catch (error) { if (!isExpectedFinanceError(error)) throw error; return { content: [{ type: "text", text: error.message }], isError: true }; } }
export function createReceivableTools(service: ReceivableService): FinanceToolDefinition[] { return [
  { name: "record_receivable", description: "Record a receivable.", isWriteOperation: true, inputSchema: { type: "object", additionalProperties: false, required: ["description", "amount", "expectedDate", "confidence"], properties: { description: text, amount: money, expectedDate: date, confidence } }, handler: (a) => run(() => service.recordReceivable(a as never), "Receivable recorded.", "receivable") },
  { name: "list_receivables", description: "List receivables.", isWriteOperation: false, inputSchema: { type: "object", additionalProperties: false, properties: { status: { type: "string", enum: ["PENDING", "COLLECTED"] }, confidence, dueBefore: date } }, handler: (a) => run(() => service.listReceivables(a as never), "Receivables listed.", "receivables") },
  { name: "update_receivable", description: "Update a receivable.", isWriteOperation: true, inputSchema: { type: "object", additionalProperties: false, required: ["receivableId"], anyOf: [{ properties: { description: text }, required: ["description"] }, { properties: { amount: money }, required: ["amount"] }, { properties: { expectedDate: date }, required: ["expectedDate"] }, { properties: { confidence }, required: ["confidence"] }], properties: { receivableId: id, description: text, amount: money, expectedDate: date, confidence } }, handler: (a) => run(() => service.updateReceivable(a as never), "Receivable updated.", "receivable") },
  { name: "mark_receivable_collected", description: "Mark a receivable as collected.", isWriteOperation: true, inputSchema: { type: "object", additionalProperties: false, required: ["receivableId"], properties: { receivableId: id } }, handler: (a) => run(() => service.markReceivableCollected(a.receivableId as number), "Receivable marked as collected.", "receivable") },
  { name: "delete_receivable", description: "Delete a receivable.", isWriteOperation: true, inputSchema: { type: "object", additionalProperties: false, required: ["receivableId"], properties: { receivableId: id } }, handler: (a) => run(() => service.deleteReceivable(a.receivableId as number), "Receivable deleted.", "receivable") },
]; }
